from pymongo import MongoClient
client = MongoClient('localhost', 27017)
db = client.get_database('retry_db')

db.movies.drop()
db.movies.insert_one({'title' : 'A', 'img-url' : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-i1TsJ0G4Y6js4IjWLRBmaiTxjWFoyBd2uw&usqp=CAU", 'link-url' : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-i1TsJ0G4Y6js4IjWLRBmaiTxjWFoyBd2uw&usqp=CAU", 'open-year' : '2022', 'open-month' : '07', 'open-day' :'27', 'aud-num' : 40, 'likes': 0, 'trashed': False})
db.movies.insert_one({'title' : 'B', 'img-url' : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlI0mnjLCCSXSevxxd9ueUHyB1gyAJuFbrZw&usqp=CAU", 'link-url' : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlI0mnjLCCSXSevxxd9ueUHyB1gyAJuFbrZw&usqp=CAU", 'open-year' : '2022', 'open-month' : '04', 'open-day' :'25', 'aud-num' : 20, 'likes': 0, 'trashed': False})
db.movies.insert_one({'title' : 'C', 'img-url' : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyGnV38qI3kabyXoa6e9eOn9960Lcnzj3jGA&usqp=CAU", 'link-url' : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyGnV38qI3kabyXoa6e9eOn9960Lcnzj3jGA&usqp=CAU", 'open-year' : '2001', 'open-month' : '03', 'open-day' :'18', 'aud-num' : 70, 'likes': 0, 'trashed': False})
db.movies.insert_one({'title' : 'D', 'img-url' : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQF5muH6piXfKA2yUyMkJwm0mJq6O4lU-1mFA&usqp=CAU", 'link-url' : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQF5muH6piXfKA2yUyMkJwm0mJq6O4lU-1mFA&usqp=CAU", 'open-year' : '2013', 'open-month' : '09', 'open-day' :'18', 'aud-num' : 50, 'likes': 0, 'trashed': False})
db.movies.insert_one({'title' : 'E', 'img-url' : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzZYkHh3xI19UcMx7wnZzWE5-EmlAGEiaVAw&usqp=CAU", 'link-url' : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzZYkHh3xI19UcMx7wnZzWE5-EmlAGEiaVAw&usqp=CAU", 'open-year' : '2015', 'open-month' : '09', 'open-day' :'15', 'aud-num' : 10, 'likes': 0, 'trashed': False})
db.movies.insert_one({'title' : 'F', 'img-url' : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgWp5q7XUxH1uCLTgegzW5XqLE23lZvpUiTeIyD3Fl5l99iBErqAlY27rPNHkSchmcPCY&usqp=CAU", 'link-url' : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgWp5q7XUxH1uCLTgegzW5XqLE23lZvpUiTeIyD3Fl5l99iBErqAlY27rPNHkSchmcPCY&usqp=CAU", 'open-year' : '2020', 'open-month' : '09', 'open-day' :'16', 'aud-num' : 70, 'likes': 0, 'trashed': False})
db.movies.insert_one({'title' : 'G', 'img-url' : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNhWseR8EZjTjl-DHoffqs1sZLrcfbZBkdPQ&usqp=CAU", 'link-url' : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNhWseR8EZjTjl-DHoffqs1sZLrcfbZBkdPQ&usqp=CAU", 'open-year' : '1999', 'open-month' : '05', 'open-day' :'05', 'aud-num' : 30, 'likes': 0, 'trashed': False})
db.movies.insert_one({'title' : 'H', 'img-url' : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZxwdXBWunQIzm4bK22zQBON37m4OObgQUmw&usqp=CAU", 'link-url' : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZxwdXBWunQIzm4bK22zQBON37m4OObgQUmw&usqp=CAU", 'open-year' : '1998', 'open-month' : '02', 'open-day' :'01', 'aud-num' : 60, 'likes': 0, 'trashed': False})
